//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sroki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Календарь.
    /// </summary>
    // *** Start programmer edit section *** (Календарь CustomAttributes)

    // *** End programmer edit section *** (Календарь CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КалендарьE", new string[] {
            "Трудозатраты as \'Трудозатраты\'",
            "Участник as \'Участник\'",
            "Участник.ФИО as \'ФИО\'",
            "Проект as \'Проект\'",
            "Проект.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Участник.ФИО",
            "Проект.Наименование"})]
    [MasterViewDefineAttribute("КалендарьE", "Участник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("КалендарьE", "Проект", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("КалендарьL", new string[] {
            "Трудозатраты as \'Трудозатраты\'",
            "Участник.ФИО as \'ФИО\'",
            "Проект.Наименование as \'Наименование\'"})]
    public class Календарь : ICSSoft.STORMNET.DataObject
    {
        
        private int fТрудозатраты;
        
        private IIS.Sroki.Участник fУчастник;
        
        private IIS.Sroki.Проект fПроект;
        
        // *** Start programmer edit section *** (Календарь CustomMembers)

        // *** End programmer edit section *** (Календарь CustomMembers)

        
        /// <summary>
        /// Трудозатраты.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.Трудозатраты CustomAttributes)

        // *** End programmer edit section *** (Календарь.Трудозатраты CustomAttributes)
        public virtual int Трудозатраты
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.Трудозатраты Get start)

                // *** End programmer edit section *** (Календарь.Трудозатраты Get start)
                int result = this.fТрудозатраты;
                // *** Start programmer edit section *** (Календарь.Трудозатраты Get end)

                // *** End programmer edit section *** (Календарь.Трудозатраты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.Трудозатраты Set start)

                // *** End programmer edit section *** (Календарь.Трудозатраты Set start)
                this.fТрудозатраты = value;
                // *** Start programmer edit section *** (Календарь.Трудозатраты Set end)

                // *** End programmer edit section *** (Календарь.Трудозатраты Set end)
            }
        }
        
        /// <summary>
        /// Календарь.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.Проект CustomAttributes)

        // *** End programmer edit section *** (Календарь.Проект CustomAttributes)
        [PropertyStorage(new string[] {
                "Проект"})]
        [NotNull()]
        public virtual IIS.Sroki.Проект Проект
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.Проект Get start)

                // *** End programmer edit section *** (Календарь.Проект Get start)
                IIS.Sroki.Проект result = this.fПроект;
                // *** Start programmer edit section *** (Календарь.Проект Get end)

                // *** End programmer edit section *** (Календарь.Проект Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.Проект Set start)

                // *** End programmer edit section *** (Календарь.Проект Set start)
                this.fПроект = value;
                // *** Start programmer edit section *** (Календарь.Проект Set end)

                // *** End programmer edit section *** (Календарь.Проект Set end)
            }
        }
        
        /// <summary>
        /// Календарь.
        /// </summary>
        // *** Start programmer edit section *** (Календарь.Участник CustomAttributes)

        // *** End programmer edit section *** (Календарь.Участник CustomAttributes)
        [PropertyStorage(new string[] {
                "Участник"})]
        [NotNull()]
        public virtual IIS.Sroki.Участник Участник
        {
            get
            {
                // *** Start programmer edit section *** (Календарь.Участник Get start)

                // *** End programmer edit section *** (Календарь.Участник Get start)
                IIS.Sroki.Участник result = this.fУчастник;
                // *** Start programmer edit section *** (Календарь.Участник Get end)

                // *** End programmer edit section *** (Календарь.Участник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Календарь.Участник Set start)

                // *** End programmer edit section *** (Календарь.Участник Set start)
                this.fУчастник = value;
                // *** Start programmer edit section *** (Календарь.Участник Set end)

                // *** End programmer edit section *** (Календарь.Участник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КалендарьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КалендарьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КалендарьE", typeof(IIS.Sroki.Календарь));
                }
            }
            
            /// <summary>
            /// "КалендарьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КалендарьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КалендарьL", typeof(IIS.Sroki.Календарь));
                }
            }
        }
    }
}
