//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sroki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проект.
    /// </summary>
    // *** Start programmer edit section *** (Проект CustomAttributes)

    // *** End programmer edit section *** (Проект CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроектE", new string[] {
            "Бюджет as \'Бюджет\'",
            "Наименование as \'Наименование\'",
            "Срок as \'Срок\'"})]
    [View("ПроектL", new string[] {
            "Бюджет as \'Бюджет\'",
            "Наименование as \'Наименование\'",
            "Срок as \'Срок\'"})]
    public class Проект : ICSSoft.STORMNET.DataObject
    {
        
        private int fБюджет;
        
        private string fНаименование;
        
        private string fСрок;
        
        // *** Start programmer edit section *** (Проект CustomMembers)

        // *** End programmer edit section *** (Проект CustomMembers)

        
        /// <summary>
        /// Бюджет.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Бюджет CustomAttributes)

        // *** End programmer edit section *** (Проект.Бюджет CustomAttributes)
        public virtual int Бюджет
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Бюджет Get start)

                // *** End programmer edit section *** (Проект.Бюджет Get start)
                int result = this.fБюджет;
                // *** Start programmer edit section *** (Проект.Бюджет Get end)

                // *** End programmer edit section *** (Проект.Бюджет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Бюджет Set start)

                // *** End programmer edit section *** (Проект.Бюджет Set start)
                this.fБюджет = value;
                // *** Start programmer edit section *** (Проект.Бюджет Set end)

                // *** End programmer edit section *** (Проект.Бюджет Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Наименование CustomAttributes)

        // *** End programmer edit section *** (Проект.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Наименование Get start)

                // *** End programmer edit section *** (Проект.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Проект.Наименование Get end)

                // *** End programmer edit section *** (Проект.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Наименование Set start)

                // *** End programmer edit section *** (Проект.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Проект.Наименование Set end)

                // *** End programmer edit section *** (Проект.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Срок.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Срок CustomAttributes)

        // *** End programmer edit section *** (Проект.Срок CustomAttributes)
        [StrLen(255)]
        public virtual string Срок
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Срок Get start)

                // *** End programmer edit section *** (Проект.Срок Get start)
                string result = this.fСрок;
                // *** Start programmer edit section *** (Проект.Срок Get end)

                // *** End programmer edit section *** (Проект.Срок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Срок Set start)

                // *** End programmer edit section *** (Проект.Срок Set start)
                this.fСрок = value;
                // *** Start programmer edit section *** (Проект.Срок Set end)

                // *** End programmer edit section *** (Проект.Срок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроектE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектE", typeof(IIS.Sroki.Проект));
                }
            }
            
            /// <summary>
            /// "ПроектL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектL", typeof(IIS.Sroki.Проект));
                }
            }
        }
    }
}
