//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sroki
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Роли.
    /// </summary>
    // *** Start programmer edit section *** (роли CustomAttributes)

    // *** End programmer edit section *** (роли CustomAttributes)
    public enum роли
    {
        
        // *** Start programmer edit section *** (роли.Руководитель CustomAttributes)

        // *** End programmer edit section *** (роли.Руководитель CustomAttributes)
        Руководитель,
        
        // *** Start programmer edit section *** (роли.Аудитор CustomAttributes)

        // *** End programmer edit section *** (роли.Аудитор CustomAttributes)
        Аудитор,
        
        // *** Start programmer edit section *** (роли.Исполнитель CustomAttributes)

        // *** End programmer edit section *** (роли.Исполнитель CustomAttributes)
        Исполнитель,
    }
}
