//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sroki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участник.
    /// </summary>
    // *** Start programmer edit section *** (Участник CustomAttributes)

    // *** End programmer edit section *** (Участник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчастникE", new string[] {
            "ФИО as \'ФИО\'",
            "Роль as \'Роль\'"})]
    [View("УчастникL", new string[] {
            "ФИО as \'ФИО\'",
            "Роль as \'Роль\'"})]
    public class Участник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Sroki.роли fРоль;
        
        // *** Start programmer edit section *** (Участник CustomMembers)

        // *** End programmer edit section *** (Участник CustomMembers)

        
        /// <summary>
        /// Роль.
        /// </summary>
        // *** Start programmer edit section *** (Участник.Роль CustomAttributes)

        // *** End programmer edit section *** (Участник.Роль CustomAttributes)
        public virtual IIS.Sroki.роли Роль
        {
            get
            {
                // *** Start programmer edit section *** (Участник.Роль Get start)

                // *** End programmer edit section *** (Участник.Роль Get start)
                IIS.Sroki.роли result = this.fРоль;
                // *** Start programmer edit section *** (Участник.Роль Get end)

                // *** End programmer edit section *** (Участник.Роль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Участник.Роль Set start)

                // *** End programmer edit section *** (Участник.Роль Set start)
                this.fРоль = value;
                // *** Start programmer edit section *** (Участник.Роль Set end)

                // *** End programmer edit section *** (Участник.Роль Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Участник.ФИО CustomAttributes)

        // *** End programmer edit section *** (Участник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Участник.ФИО Get start)

                // *** End programmer edit section *** (Участник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Участник.ФИО Get end)

                // *** End programmer edit section *** (Участник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Участник.ФИО Set start)

                // *** End programmer edit section *** (Участник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Участник.ФИО Set end)

                // *** End programmer edit section *** (Участник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчастникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникE", typeof(IIS.Sroki.Участник));
                }
            }
            
            /// <summary>
            /// "УчастникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникL", typeof(IIS.Sroki.Участник));
                }
            }
        }
    }
}
